I116 shared quiz models app
codersforcauses/elucidate pull request #120
Opened 2022-07-16 14:17 UTC by cjnbennett

## Change Summary
Implemented several quiz and statistics models (and their respective serializers) that will be shared between the various quiz apps (#72, #73, #74). This issue is a priority so that the other quiz-related issues can continue work with a definite set of models. The documentation goes into the details of these models and how they are intended to be used.

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [x] The change has tests
- [x] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2022-07-16 14:50 UTC, cjnbennett commented
There are still some linting "issues" in the code (hence why the linting test failed), those are files automatically generated by Django for the purpose of database migrations, so I have not touched them. There are no linting issues in any other files.

2022-07-18 14:49 UTC, jsun1590 commented
> There are still some linting "issues" in the code (hence why the linting test failed), those are files automatically generated by Django for the purpose of database migrations, so I have not touched them. There are no linting issues in any other files.

@cjnbennett Could you still run linting on those in the future please?

You can do `black . --line-length 79 --preview`

2022-07-19 05:34 UTC, jsun1590 requested changes
Well done, great job overall! Just a couple of small changes needed :)

2022-07-19 05:34 UTC, jsun1590 commented on server/api/apps/shared_models/apps.py
> +from django.apps import AppConfig
apps.py is not needed if you are directly installing the app in settings.py and not changing other configurations. Alternatively, when installing the app reference the config file.
https://stackoverflow.com/a/46346843

2022-07-19 05:34 UTC, jsun1590 commented on server/api/apps/shared_models/models/quiz_models.py
> +from django.utils.translation import gettext_lazy as _
Translations are not included in the MVP scope currently, so we don't really need to use this

2022-07-19 05:34 UTC, jsun1590 commented on server/api/apps/shared_models/models/quiz_models.py
> +from django.contrib.auth.models import User
We are using a custom User model in the project. Please see this: https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#referencing-the-user-model

2022-07-19 05:34 UTC, jsun1590 commented on server/api/apps/shared_models/models/statistics_models.py
> +from django.contrib.auth.models import User
https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#referencing-the-user-model

2022-07-19 09:46 UTC, jsun1590 approved these changes
Thanks, looks great! Feel free to merge :+1:

2022-07-19 09:49 UTC, merged