[WIP] I119 integrate backend and frontend signup
codersforcauses/elucidate pull request #122
Opened 2022-07-17 15:35 UTC by jsun1590

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2022-07-21 14:22 UTC, CodeWithTheDoctor commented
The form doesn't seem to be functional.

I tried submitting this on the vercel deployment:
![image](https://user-images.githubusercontent.com/22740095/180237718-57f20c41-1d62-4f17-bb56-b05d6758dbe1.png)

And the following error gets logged:
![image](https://user-images.githubusercontent.com/22740095/180237864-d3dc3e87-fd42-47fe-8a6c-eabf3a30862f.png)

2022-07-22 01:06 UTC, CodeWithTheDoctor commented
Omg, I totally forgot about that! I'll have a look again hahaha

On Thu, 21 Jul 2022, 11:31 pm jsun1590, ***@***.***> wrote:

> Can't deploy Django backend on Vercel unfortunately, so only the frontend
> is working, will endeavour to have AWS deployments done soon, but preview
> branches may still prove to be a challenge.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/codersforcauses/elucidate/pull/122#issuecomment-1191634997>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNPY72MOYYDOKVP6DXHFFLVVFUNDANCNFSM53Z5VGVA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-07-22 01:55 UTC, jsun1590 commented
But I should prolly handle errors on time out to backend, good point

2022-07-23 06:25 UTC, CodeWithTheDoctor requested changes
Small changes, but everything else looks good

2022-07-23 06:25 UTC, CodeWithTheDoctor commented on client/cypress/e2e/auth/signup.spec.cy.js
> +    cy.get('input[name="First Name"').type('John');
Missing closing brackets.... mmmmmmm (yoda voice)

2022-07-23 06:25 UTC, CodeWithTheDoctor commented on server/api/settings.py
> +    # "DEFAULT_PERMISSION_CLASSES": (
I reckon get rid of unnecessary comments. Unless you think its sustainable

2022-07-23 06:31 UTC, CodeWithTheDoctor approved these changes
Looks good! send it in

2022-07-23 06:33 UTC, merged