I99 user dashboard page
codersforcauses/elucidate pull request #130
Opened 2022-07-19 06:07 UTC by jsun1590

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2022-07-25 03:39 UTC, otta8634 commented on client/nuxt.config.js
> -      '~/components/Auth',
Add back

2022-07-25 03:40 UTC, otta8634 commented on client/nuxt.config.js
> -      '~/components/Auth',
@jsun1590 fixed this

2022-07-25 03:53 UTC, otta8634 approved these changes
@jsun1590 told me to.

2022-07-27 07:15 UTC, CodeWithTheDoctor requested changes
Small changes needed, otherwise everything else looks great and ready to me merged!

2022-07-27 07:15 UTC, CodeWithTheDoctor commented on client/components/Quiz/QuizList.vue
> +    <div class="grid grid-rows-auto mr-10 flex space-y-2">
There is `grid` and `flex` in the same element..... 
Might wanna check that because `grid` and `flex` are two different display types.

2022-07-27 07:15 UTC, CodeWithTheDoctor commented on client/components/Quiz/QuizList.vue
> +      <div class="py-1 px-6 grid grid-cols-7 text-lightgrey font-bold flex">
Same here

2022-08-07 10:46 UTC, jsun1590 commented on client/test/Input/SearchBar.spec.js
>  import SearchBar from '@/components/Input/SearchBar.vue';
Those are Jest tests and should not be deleted

2022-08-07 11:00 UTC, jsun1590 commented
lgtm

2022-08-07 11:00 UTC, merged